# Path to your oh-my-zsh installation.
export ZSH=$XDG_CONFIG_HOME/zsh/oh-my-zsh
export ZSH_CUSTOM=$ZSH/../custom

ZSH_THEME="robbyrussell"
DISABLE_AUTO_UPDATE="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=(git zsh-syntax-highlighting)

# User configuration

source $ZSH/oh-my-zsh.sh

export BROWSER=firefox
export TERMCMD=urxvtc # Which terminal ranger uses to start an application in
export GTK_THEME=Adwaita

alias octave="octave --no-gui"

alias vi=vim
if [[ -x $(which nvim) ]]; then
  export VISUAL=nvim
  alias vim=nvim
else
  export VISUAL=vim
fi

if [[ -x $(which most) ]]; then
  export PAGER=most
fi

# Be greeted with a fortune cookie :)
if [[ -x $(which fortune) && -x $(which cowthink) && -x $(which lolcat) ]]; then
  command fortune -s | cowthink -f tux -W `expr $(stty size | cut -d " " -f 2) - 3` | lolcat
fi
